"""sync models

Revision ID: 096fd098c38e
Revises: 
Create Date: 2026-02-07 22:17:04.244939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096fd098c38e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('entity', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_credit_scores_id'), 'credit_scores', ['id'], unique=False)
    op.create_index(op.f('ix_score_rules_id'), 'score_rules', ['id'], unique=False)
    op.create_index(op.f('ix_user_consents_id'), 'user_consents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_consents_id'), table_name='user_consents')
    op.drop_index(op.f('ix_score_rules_id'), table_name='score_rules')
    op.drop_index(op.f('ix_credit_scores_id'), table_name='credit_scores')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity')
    # ### end Alembic commands ###
